name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_KEY }}
          passphrase: ${{ secrets.CPANEL_SSH_PASSPHRASE }}
          script: |
            cd ~/public_html
            if [ ! -d "kharjamaat.patelinfotech.online/.git" ]; then
              git clone git@github.com:officialpatelinfotech/kharjamaat.git kharjamaat.patelinfotech.online
            else
              cd kharjamaat.patelinfotech.online
              git fetch --all
              git reset --hard origin/main
            fi
            composer install --no-dev --optimize-autoloader